sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t enygaard/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true enygaard/docker-react npm run test